server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
  registerDefaultExceptionMappers: false

# Logging settings.
logging:
  level: INFO
  loggers:
    com.github: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "%-5level [%date{ISO8601}] [%thread]: %c - %msg%n"